### ISSUE TITLE
build failed on ubuntu 20.04  kernel 5.4 with clang 10.

### ISSUE THREAD

**Issue by cfc4n** [ehids/ecapture#256]
**Describe the bug**
build failed on ubuntu 20.04  kernel 5.4 with clang 10.
```shell
In file included from kern/openssl_1_1_1a_kern.c:45:
In file included from ./kern/openssl.h:1:
In file included from ./kern/ecapture.h:41:
In file included from /lib/modules/5.4.0-131-generic/build/include/uapi/linux/ptrace.h:143:
In file included from /lib/modules/5.4.0-131-generic/build/arch/x86/include/asm/ptrace.h:5:
/lib/modules/5.4.0-131-generic/build/arch/x86/include/asm/segment.h:266:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^
/lib/modules/5.4.0-131-generic/build/arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
        asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
        ^
/lib/modules/5.4.0-131-generic/build/include/linux/compiler_types.h:214:24: note: expanded from macro 'asm_inline'
#define asm_inline asm __inline
```

**To Reproduce**
1. apt install clang llvm make
2. git clone
3. make nocore

**Expected behavior**
build success.

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: [e.g. Ubuntu 20.04]
- Arch: [e.g. x86 64]
- Kernel Version: [e.g. 5.4]
- Version: [e.g. 0.4.7-master]

**Additional context**

ref: 

- [Missing support for asm_inline in Linux 5.4](https://github.com/iovisor/bcc/issues/2546)
- [Redefine asm_inline for Linux 5.4+, Fixes](https://github.com/iovisor/bcc/pull/2547/files)
- [asm __inline usage on newer kernels (5.10.x) ](https://github.com/iovisor/bcc/issues/3244)
- [Most BCC tools broken on Ubuntu 18.04 when running kernel 5.4 or above](https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/12052)
- [bcc-tools fail to compile on 5.4.7-200 kernel](https://bugzilla.redhat.com/show_bug.cgi?id=1788228)
